name: Build Artifacts

on:
  push:
    tags:
      - v*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build publishable jar
        run: sbt publish
      - name: Upload package
        uses: actions/upload-artifact@v1
        with:
          name: RomanNumerals
          path: /home/runner/work/RomanNumeralsInScala/RomanNumeralsInScala/target/scala-2.13
